package: d2u_address
version: '1.0.0'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_address

page:
    title: 'translate:d2u_address'
    perm: d2u_address[]
    icon: rex-icon fa-address-card
    subpages:
        address: { title: 'translate:d2u_address_adress', icon: rex-icon fa-address-card }
        address_type: { title: 'translate:d2u_address_adress_types', icon: rex-icon fa-address-book }
        countries: { title: 'translate:d2u_address_countries', icon: rex-icon fa-flag }
        zip_codes: { title: 'translate:d2u_address_zip_codes', icon: rex-icon fa-road }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_address[settings] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_address[settings] }

requires:
    redaxo: '>=5.3.0'
    php:
        version: '>=5.6'
    packages:
        d2u_helper: '>=1.2.4'
        sprog: '>=1.0.0'